locales:
  default: fr-fr
spawn: "world:0:-60:0:0:0"
game:
  starting-time: 10
  min-players: 1
  max-players: 10
  beacon:
    spawn: "world:8:-51:8:0:0"
    default-health: 50.0
    protection:
      health: 200.0
      schematic-file: 'defense.schem'
      schematic-paste-location: 'world:10:-53:10:0:0'
      end-crystals-amount: 4
      end-crystals-locations:
        - 'world:-7.5:-59:24.5:0:0'
        - 'world:-7.5:-59:-7.5:0:0'
        - 'world:24.5:-59:-7.5:0:0'
        - 'world:24.5:-59:24.5:0:0'
    max-base-placements: 2
  scoreboard:
    phase-1:
      title: "game.scoreboard.title"
      lines:
        - "game.scoreboard.remaining-time"
        - ""
        - "game.scoreboard.current-objective"
        - ""
        - "game.scoreboard.role"
        - "game.scoreboard.next-event"
    phase-2:
      title: "game.scoreboard.title"
      lines:
        - "game.scoreboard.remaining-time"
        - ""
        - "game.scoreboard.current-objective"
        - ""
        - "game.scoreboard.role"
        - "game.scoreboard.next-event"
